### ISSUE TITLE
A Porblem about batch operation of the JDBC. 

### ISSUE THREAD

**Issue by bmmcq** [hannesmuehleisen/MonetDBLite-Java#1]
I executed a batch load operation in JDBC api, and inserted about 100818 records . After the batch is commited successfully, i found only one record is really inserted. What's the problem ?

**Comment by PedroTadim** [comment]
It is said in the documentation that Batch processing is not properly supported. The problem has to do with the original MonetDB JDBC driver implementation. I will look at it again to see if I can make it possible easily.

**Comment by PedroTadim** [comment]
I found it straightforward to implement actually. I shall make a new release later today.

**Comment by PedroTadim** [comment]
May I close this issue?
