### ISSUE TITLE
Segfault in appendColumns

### ISSUE THREAD

**Issue by kraftp** [hannesmuehleisen/MonetDBLite-Java#5]
There's what seems to be a serious issue in line 460 of converters.c.  The loop iterates through an array, but each iteration increments both the array pointer (p) and the index into the array (i).  Since the number of iterations is equal to the length of the array, this causes the pointer to run off the end of the array, leading to segfaults when the array is very large (say, when appending a large column).  I fixed this (three-character change) in my fork and it eliminated segfaults I was experiencing.

**Comment by PedroTadim** [comment]
Hello @kraftp , thanks for catch! I already did the fix, and next week we will start the process of making a new release.

**Comment by PedroTadim** [comment]
Just made 2.39 release with the fix.

**Comment by kraftp** [comment]
Thank you!  It fixes the problems I was having.
