### ISSUE TITLE
Possible bug with control characters in the new driver

### ISSUE THREAD

**Issue by davidcorcoran** [hannesmuehleisen/MonetDBLite-Java#7]
Hi @PedroTadim ,

I've been using the `monetdb-jdbc` 2.29 driver on my project and was looking at switching to using either `monetdb-java-lite` embedded or `monetdb-java-new`. However I've found a problem reading in a `VARCHAR` where a control character is being wrongly interpreted and ending up as two characters.

The writing of the control character (`FS`, [file separator](https://theasciicode.com.ar/ascii-control-characters/file-separator-ascii-code-28.html), hex `1C`) is fine. When I query the database using the old 2.29 driver it looks fine too. However if I query it using the new driver the single `FS` character is translated into two characters, `"34"`. Which, weirdly, is the octal representation of `1C`.

It can be simply reproduced with this query (28 being the decimal representation of `FS`):
`SELECT concat(CODE(28), 'asdf');` 
If you run that using the 2.29 driver you correctly get `asdf`. If you run it using the new driver you get `34asdf`.

This is all running against Monet 11.31.13, which is running in a Docker container on the same machine (`jdbc:monetdb://localhost:50000/`). I don't see the problem if I run using `embedded`.

Any help would be greatly appreciated.

Thanks

(In case it helps, I'm using the control character `FS`  to escape some characters in a string before it's written to Monet. For example replacing `/` with `FS` in `/test/string`. When I read that back out of Monet with the new driver I get `34test34string`.)

**Comment by PedroTadim** [comment]
Hello David, I just made a fix to the mapi protocol handling here: https://dev.monetdb.org/hg/monetdb-java/rev/d6792323e680 You can compile the driver by source for now (it shouldn't be complicated), otherwise I can make a release soon.

**Comment by davidcorcoran** [comment]
Ah excellent thank you. Now I see why it was coming out as octal :)

I'll try building from source this week and otherwise wait for the release if I fail. I'm seeing some great speed improvements using the embedded driver so I'm keen to be able to use the new and lite driver for both running embedded, and connecting to a running Monet, with just some config changes.

Thank you for the amazingly fast turn-around.
